name: Dependency Scan

on:
  workflow_call:

jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Trivy Vulnerability Scanner
        uses: aquasecurity/trivy-action@0.28.0  # Uses a pinned, reliable version
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table'
          severity: 'CRITICAL,HIGH'
          exit-code: '1' # Fails the GitHub build if high or critical vulnerabilities are found

