name: Dependency Scan

on:
  workflow_call:

jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # 🔧 Install Java (Dependency-Check needs Java)
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      

      - name: Run Dependency Check
        run: |
          mkdir -p reports
          docker run --rm \
            -v $(pwd):/src \
            -v $(pwd)/reports:/report \
            owasp/dependency-check \
            --project "skillpulse" \
            --scan /src \
            --format HTML \
            --out /report
            --noupdate

      # 📤 Upload Report
      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-report
          path: reports
