name: Docker Lint

on:
  push:
    paths:
      - 'backend/Dockerfile'
      - 'frontend/Dockerfile'
  pull_request:

jobs:
  docker-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Lint Backend Dockerfile
        run: |
          docker run --rm -i hadolint/hadolint < backend/Dockerfile

      - name: Lint Frontend Dockerfile
        run: |
          docker run --rm -i hadolint/hadolint < frontend/Dockerfile
