name: Docker Lint

on:
  workflow_call:
  pull_request:

jobs:
  docker-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Lint Backend Dockerfile
        run: |
          docker run --rm \
          -v ${{ github.workspace }}/backend/Dockerfile:/Dockerfile \
          hadolint/hadolint hadolint /Dockerfile      
      - name: Lint Frontend Dockerfile
        run: |
          docker run --rm \
          -v ${{ github.workspace }}/frontend/Dockerfile:/Dockerfile \
          hadolint/hadolint hadolint /Dockerfile
