name: Docker Lint

on:
  workflow_call:
  pull_request:

jobs:
  docker-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Lint Backend Dockerfile
        run: |
          docker run --rm -i hadolint/hadolint hadolint --failure-threshold warning < backend/Dockerfile
      - name: Lint Frontend Dockerfile
        run: |
          docker run --rm -i hadolint/hadolint hadolint --failure-threshold warning < frontend/Dockerfile
